# Web Socket Configuration
gos_web_socket:
    server:
        port: 1337        #The port the socket server will listen on
        host: 172.22.0.3  #The host ip to bind to
        router:
            resources:
                - 'ws_routes.yaml'
